eureka:
  client:
    fetchRegistry: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      instance:
        hostname: localhost
zuul:
  routes:
    product:
      path: /product-microservice/**
      sensitive-headers:
      service-id: product-microservice
    booking:
      path: /booking-microservice/**
      sensitive-headers:
      service-id: booking-microservice
    uaa:
      path: /uaa/**
      sensitive-headers:
      service-id: micro-uaa

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:7777/user